"""Extract hash-checked plotting records from evidence shards, without simulations."""

import argparse
import gzip
import hashlib
import json
from pathlib import Path

import numpy as np

from agcws.evidence import catalog, packs

ROOT = Path(__file__).resolve().parents[2]


def checksum(data):
    return hashlib.sha256(data).hexdigest()


def extract_tasks():
    """Copy evaluated vectors, checking bank and plan hashes without regenerating targets."""
    result = {}
    for design in ("aes", "dma", "ibex", "mesh", "redmule"):
        bank_path = catalog.design(ROOT, design, 'bank')
        plan = catalog.design(ROOT, design, 'plan')
        sources = {name: path for name, path in (
            ("bank", bank_path), ("config", plan / "config.json"),
            ("manifest", plan / "manifest.json"), ("freeze", plan / "freeze.json"))}
        data = {name: json.loads(path.read_text()) for name, path in sources.items()}
        bank, config, manifest, freeze = (data[k] for k in ("bank", "config", "manifest", "freeze"))
        if checksum(bank_path.read_bytes()) != freeze["bank_sha256"]:
            raise ValueError(f"{design}: frozen bank hash mismatch")
        if checksum(sources["manifest"].read_bytes()) != freeze["manifest_sha256"]:
            raise ValueError(f"{design}: frozen manifest hash mismatch")
        for key in ("targets", "scale", "domain", "tolerance", "success_metric"):
            if config[key] != manifest["spec"][key]:
                raise ValueError(f"{design}: plan/manifest mismatch for {key}")
        targets = {"confirmation-" + row["id"]: row["rates"]
                   for row in bank["splits"]["confirmation"]["requests"]}
        if (targets != config["targets"] or bank["calibration"]["scale"] != config["scale"]
                or bank["domain"] != config["domain"]):
            raise ValueError(f"{design}: bank/plan mismatch")
        result[design] = {
            "domain": config["domain"], "scale": config["scale"],
            "tolerance": config["tolerance"], "targets": targets,
            "calibration": bank["calibration"], "runtime_commit": freeze["runtime_commit"],
            "sources": {name: {"path": str(path.relative_to(ROOT)), "sha256": checksum(path.read_bytes())}
                        for name, path in sources.items()},
        }
    return result


def write_tasks():
    tasks = extract_tasks()
    output = ROOT / "paper/evidence"
    output.mkdir(parents=True, exist_ok=True)
    (output / "task_vectors.json").write_text(json.dumps(tasks, indent=2) + "\n")
    lines = ["# Frozen evaluated target vectors", "",
             "Generated by `paper/scripts/extract.py` from hash-checked banks and evaluated plans.",
             "No target generation or simulation. Values below are rounded to six decimals;",
             "[task_vectors.json](task_vectors.json) retains original precision and source hashes.",
             "Rates are known bit transitions per cycle, not watts. Flat controls are separate",
             "from the eight nonflat tasks. Tolerance is 0.05 times the design's fixed scale.", ""]
    for design, task in tasks.items():
        cal = task['calibration']
        lines += [f"## {design.upper()} ({task['domain']})", "",
                  f"Scale: {task['scale']:.6f}. Valid calibration workloads: {cal['valid']}/{cal['proposals']}.",
                  f"Bank: [{task['sources']['bank']['path']}](../../{task['sources']['bank']['path']}).", "",
                  "| Profile | Eight requested bin rates | Mean |", "|---|---|---:|"]
        for name, values in task['targets'].items():
            lines.append(f"| {name.removeprefix('confirmation-')} | "
                         + ", ".join(f"{v:.6f}" for v in values)
                         + f" | {sum(values) / len(values):.6f} |")
        lines.append("")
    (output / "task_vectors.md").write_text("\n".join(lines) + "\n")




def extract(recipe):
    sources = {}
    for archive_name in sorted({s["archive"] for s in recipe["sources"].values()}):
        archive = catalog.resolve(ROOT, archive_name)
        metadata = packs.manifest(archive)
        prefixes = [f"panel/{target}/{recipe['seed']}/{s['arm']}/"
                    for s in recipe["sources"].values() if s["archive"] == archive_name
                    for target in recipe["targets"]]
        inventory_name = "inventory.json" if "inventory.json" in metadata["files"] else "inventory.json.gz"
        names = {"manifest.json.gz", inventory_name}
        names.update(n for n in metadata["files"] if any(n.startswith(p) for p in prefixes)
                     and n.endswith(("/complete.json.gz", "/trials.json.gz", "/response.json.gz")))
        compressed = packs.read_selected(archive, names)
        raw = {n.removesuffix(".gz"): gzip.decompress(d) if n.endswith(".gz") else d
               for n, d in compressed.items()}
        inventory = json.loads(raw["inventory.json"])
        for name, data in raw.items():
            if name != "inventory.json" and checksum(data) != inventory[name]:
                raise ValueError(f"raw evidence checksum differs: {name}")
        sources[archive_name] = (raw, {n: json.loads(d) for n, d in raw.items()}, metadata)
    reference_source = next(iter(recipe["sources"].values()))
    reference = sources[reference_source["archive"]][1]["manifest.json"]
    spec = reference["spec"]
    output = {"scope": recipe["scope"], "selection": recipe["selection"],
              "recipe_sha256": packs.sha(ROOT / "paper/evidence/figure_recipe.json"),
              "design": recipe["design"], "seed": recipe["seed"], "scale": spec["scale"], "cases": []}
    for target in recipe["targets"]:
        case = {"target": target, "target_rates": spec["targets"][target], "arms": {}}
        for label, source in recipe["sources"].items():
            raw, records, metadata = sources[source["archive"]]
            manifest = records["manifest.json"]
            if manifest["runtime"] != reference["runtime"] or manifest["schema"] != reference["schema"]:
                raise ValueError("runtime or workload schema mismatch")
            for key in ("scale", "tolerance", "budget", "success_metric", "targets"):
                if manifest["spec"][key] != spec[key]:
                    raise ValueError(f"task mismatch: {label}/{key}")
            prefix = f"panel/{target}/{recipe['seed']}/{source['arm']}/"
            complete = records[prefix + "complete.json"]
            identity = complete["cell"]
            if (identity["target"], identity["seed"], identity["arm"]) != (target, recipe["seed"], source["arm"]):
                raise ValueError("completion cell identity mismatch")
            rows, slots = [], []
            for name, trials in sorted(records.items()):
                if not name.startswith(prefix) or not name.endswith("/trials.json"):
                    continue
                first = int(Path(name).parent.name)
                for offset, trial in enumerate(trials):
                    slot = first + offset
                    slots.append(slot)
                    if trial["valid"]:
                        rates = np.asarray(trial["rates"], dtype=float)
                        if rates.shape != (8,) or not np.isfinite(rates).all():
                            raise ValueError("invalid waveform")
                        error = float(np.max(np.abs((rates - case["target_rates"]) / spec["scale"])))
                        rows.append((error, slot, trial, name))
            if sorted(slots) != list(range(1, complete["charged_slots"] + 1)):
                raise ValueError("incomplete or duplicate proposal sequence")
            error, slot, trial, name = min(rows, key=lambda r: (r[0], r[1]))
            if not np.isclose(error, complete["best_max_bin_error"], rtol=0, atol=1e-10):
                raise ValueError("completion/trace discrepancy")
            response = records.get(str(Path(name).parent / "response.json"), {})
            case["arms"][label] = {
                "rates": trial["rates"], "max_bin_error": error, "selected_slot": slot,
                "charged_slots": complete["charged_slots"], "profile": trial["profile"],
                "program": trial.get("canonical_program"), "model": response.get("model_version"),
                "source_archive": source["archive"], "source_member": name,
                "source_sha256": checksum(raw[name]), "manifest_sha256": checksum(raw["manifest.json"]),
                "shards": metadata["shards"],
            }
        profiles = [row["profile"] for row in case["arms"].values()]
        for profile in profiles[1:]:
            for key in ("clock_edges", "bin_edges", "scope", "activity_contract", "window",
                        "timescale", "period_ticks", "begin_tick", "end_tick", "exclusions"):
                if profile[key] != profiles[0][key]:
                    raise ValueError(f"observation contract mismatch: {key}")
        output["cases"].append(case)
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    recipe = json.loads((ROOT / "paper/evidence/figure_recipe.json").read_text())
    output = extract(recipe)
    (ROOT / "paper/evidence/mesh_examples.json").write_text(json.dumps(output, indent=2, sort_keys=True) + "\n")
    write_tasks()
    print(f"Extracted {len(output['cases'])} cases and {len(recipe['sources'])} policies "
          "from verified archives; no simulation or API calls.")


if __name__ == "__main__":
    main()
