#!/usr/bin/env python3
"""Generate deterministic memory-macro collateral from a Yosys inventory.

This deliberately emits a manifest and black-box contracts, not a fabricated
SRAM implementation. A later backend can map each contract to bsg_fakeram (or
another characterized macro) once its port semantics are confirmed.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def generate(inventory_path: Path, output_dir: Path, *, backend: str = "bsg_fakeram") -> dict:
    data = json.loads(inventory_path.read_text())
    output_dir.mkdir(parents=True, exist_ok=True)
    macros = []
    for index, memory in enumerate(data.get("memories", [])):
        width = memory.get("width")
        depth = memory.get("size")
        abits = memory.get("abits")
        if not all(isinstance(value, int) and value > 0 for value in (width, depth, abits)):
            raise ValueError(f"memory has incomplete geometry: {memory.get('name')}")
        name = f"agcws_mem_{index}_{memory['name'].replace('$', 'mem_')}"
        macros.append({
            "source_module": memory["module"],
            "source_name": memory["name"],
            "macro_module": name,
            "backend": backend,
            "width": width,
            "depth": depth,
            "address_bits": abits,
            "read_ports": memory.get("rd_ports", 0),
            "write_ports": memory.get("wr_ports", 0),
            "status": "contract-only",
        })
    manifest = {
        "schema": 1,
        "top": data.get("top"),
        "inventory": str(inventory_path),
        "backend": backend,
        "macros": macros,
        "mapping_ready": False,
        "note": "Contracts require a verified bsg_fakeram wrapper and Liberty model before use in synthesis.",
    }
    (output_dir / "memory-macros.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    lines = ["// Generated by scripts/generate_memory_collateral.py", "// Contract-only: do not use for power claims."]
    for macro in macros:
        lines.extend([
            f"module {macro['macro_module']} (",
            f"  input wire clk, input wire [{macro['address_bits'] - 1}:0] addr,",
            f"  input wire [{macro['width'] - 1}:0] din, input wire we,",
            f"  output wire [{macro['width'] - 1}:0] dout",
            ");",
            "  // Implement with a characterized macro backend before mapping.",
            "endmodule",
            "",
        ])
    (output_dir / "memory_macros.v").write_text("\n".join(lines))
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("inventory", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--backend", default="bsg_fakeram")
    args = parser.parse_args()
    result = generate(args.inventory, args.output, backend=args.backend)
    print(json.dumps({"out": str(args.output), "macros": len(result["macros"])}, sort_keys=True))


if __name__ == "__main__":
    main()
